[package]
name = "cmdocker"
version = "0.1.0"
authors = ["alex <alex@pdp7.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "2.0.2"
users = "0.9.1"
structopt = "0.3.13"
confy = "0.4.0"
serde = { version = "1.0.106", features = ["derive"] }
atty = "0.2.14"

[dev-dependencies]
tempdir = "0.3.7"
assert_cmd = "1.0.1"
which = "3.1.1"
