[package]
name = "cmdainer"
version = "0.1.0"
authors = ["alex <alex@pdp7.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "5.0.1"
confy = "0.5.1"
serde = { version = "1.0.185", features = ["derive"] }
clap = { version = "4.3.24", features = ["derive"] }
which = "4.4.0"

[target.'cfg(not(windows))'.dependencies]
users = "0.11.0"

[dev-dependencies]
tempfile = "3.8.0"
assert_cmd = "2.0.12"
