[package]
name = "cmdocker"
version = "0.1.0"
authors = ["alex <alex@pdp7.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "3.0.1"
structopt = "0.3.21"
confy = "0.4.0"
serde = { version = "1.0.118", features = ["derive"] }
atty = "0.2.14"

[target.'cfg(not(windows))'.dependencies]
users = "0.11.0"

[dev-dependencies]
tempdir = "0.3.7"
assert_cmd = "1.0.2"
which = "4.0.2"
