[package]
name = "cmdainer"
version = "0.1.0"
authors = ["alex <alex@pdp7.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "5.0.1"
confy = "0.5.1"
serde = { version = "1.0.163", features = ["derive"] }
atty = "0.2.14"
clap = { version = "4.3.3", features = ["derive"] }

[target.'cfg(not(windows))'.dependencies]
users = "0.11.0"

[dev-dependencies]
tempfile = "3.6.0"
assert_cmd = "2.0.11"
which = "4.4.0"
